Switch to OneTrust Cookie Consent
reactor/projectreactor.io pull request #64
Opened 2021-04-27 21:42 UTC by jacksoncvm

2021-05-12 18:59 UTC, jacksoncvm commented
@simonbasle Please review

2021-05-17 09:13 UTC, simonbasle requested changes

2021-05-17 09:13 UTC, simonbasle commented on src/main/resources/static/templates/layout.html
> +    <script src='//www.vmware.com/files/templates/inc/utag_data.js'></script>
missing `https:` before the `//` here and on line 23?

2021-05-17 09:13 UTC, simonbasle commented on src/main/resources/static/templates/layout.html
> +                    <a class="ot-sdk-show-settings">Cookie Settings</a>
this doesn't seem to do anything, when running the site locally, even with the above `https:` modification (which would supposedly bring in the OT sdk) 🤔

2021-05-17 09:13 UTC, simonbasle commented on src/main/resources/static/templates/layout.html
> +    <script src='//www.vmware.com/files/templates/inc/utag_data.js'></script>
also, these scripts seem like they might be heavily `vmware.com` oriented. can you confirm they're supposed to work on other domains?

2021-05-17 09:14 UTC, simonbasle commented
thanks for the PR @jacksoncvm. I added a couple of comments/questions.

2021-05-26 12:52 UTC, merged

2021-05-26 12:53 UTC, simonbasle commented
I was able to test it on a temporary deployment, and it turns out I had some adblocker preventing the cookie consent settings to pop up.